<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>MagicLink.Aws</AssemblyName>
    <RootNamespace>Padi.Services.Authentication.MagicLink.Aws</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="4.0.103" />
    <PackageReference Include="AWSSDK.SimpleEmailV2" Version="4.0.102.1" />
    <PackageReference Include="AWSSDK.SimpleNotificationService" Version="4.0.100.7" />
    <PackageReference Include="AWSSDK.CognitoIdentityProvider" Version="4.0.103.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MagicLink.Shared\MagicLink.Shared.csproj" />
  </ItemGroup>
</Project>
