<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>MagicLink.Shared</AssemblyName>
    <RootNamespace>Padisso.MagicLink.Shared</RootNamespace>
  </PropertyGroup>
</Project>
